name: CRP-Animations
version: '${project.version}'
main: me.towster.crpanimations.CRPAnimations
api-version: 1.15
authors: [ Towster ]

commands:
  anim:
    description: Starts Animation
    usage: /anim
  save-data:
    description: saves armorstand armor data
    usage: /save-data